#Site-wide data settings

name: C. Chase Bolt
degree: Ph.D.
self_pic_title: drbolt.jpg
description_brief: Developmental geneticist
description_long:
job_title: Post doctoral researcher
institution_name: École Polytechnique Fédérale de Lausanne
institution_URL: https://www.epfl.ch/
lab_name: Duboule Laboratory of Developmental Genetics
lab_URL: http://duboule-lab.epfl.ch/home
email: ccbolt@gmail.com


# Build settings
markdown: kramdown
permalinks: pretty
exclude: [archive_of_web_work/, gulp/, css/build/]
