# Site settings
title: Chase Bolt
email: ccbolt@gmail.com
url: "http://chasebolt.com" # the base hostname & protocol for your site
twitter_username: chasebolt
github_username:  drbolt

# Build settings
markdown: kramdown
