#Site-wide data settings

name: Chase Bolt
degree: Ph.D.
self_pic_title: drbolt.jpg
description_brief: Developmental biologist
description_long:
job_title: Post doctoral researcher
lab_name: École Polytechnique Fédérale de Lausanne
lab_URL: http://www.epfl.ch/
email: ccbolt@gmail.com


# Build settings
markdown: kramdown
permalinks: pretty
baseurl: http://chasebolt.com/draft/jekyll