#Site-wide data settings

name: C. Chase Bolt
degree: Ph.D.
self_pic_title: drbolt.jpg
description_brief: Developmental biologist
description_long:
job_title: Post doctoral researcher
lab_name: Duboule Laboratory of Developmental Genomics
lab_URL: http://duboule-lab.epfl.ch/home
email: ccbolt@gmail.com


# Build settings
markdown: kramdown
permalinks: pretty